//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka
    {
        public int Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual MeterType MeterType { get; set; }
        public override string ToString()
        {
            return Person + " " + MeterType;
        }
    }
}
